/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.baracho.hm.infrastructure.config.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreateBookingAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1611659043167618035L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateBookingAvro\",\"namespace\":\"br.com.baracho.hm.infrastructure.config.kafka.avro\",\"fields\":[{\"name\":\"idBooking\",\"type\":\"string\",\"logicalType\":\"uuid\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreateBookingAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateBookingAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreateBookingAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreateBookingAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreateBookingAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreateBookingAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreateBookingAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreateBookingAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreateBookingAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence idBooking;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateBookingAvro() {}

  /**
   * All-args constructor.
   * @param idBooking The new value for idBooking
   */
  public CreateBookingAvro(java.lang.CharSequence idBooking) {
    this.idBooking = idBooking;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idBooking;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idBooking = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idBooking' field.
   * @return The value of the 'idBooking' field.
   */
  public java.lang.CharSequence getIdBooking() {
    return idBooking;
  }


  /**
   * Sets the value of the 'idBooking' field.
   * @param value the value to set.
   */
  public void setIdBooking(java.lang.CharSequence value) {
    this.idBooking = value;
  }

  /**
   * Creates a new CreateBookingAvro RecordBuilder.
   * @return A new CreateBookingAvro RecordBuilder
   */
  public static br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder newBuilder() {
    return new br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder();
  }

  /**
   * Creates a new CreateBookingAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateBookingAvro RecordBuilder
   */
  public static br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder newBuilder(br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder other) {
    if (other == null) {
      return new br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder();
    } else {
      return new br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder(other);
    }
  }

  /**
   * Creates a new CreateBookingAvro RecordBuilder by copying an existing CreateBookingAvro instance.
   * @param other The existing instance to copy.
   * @return A new CreateBookingAvro RecordBuilder
   */
  public static br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder newBuilder(br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro other) {
    if (other == null) {
      return new br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder();
    } else {
      return new br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreateBookingAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateBookingAvro>
    implements org.apache.avro.data.RecordBuilder<CreateBookingAvro> {

    private java.lang.CharSequence idBooking;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idBooking)) {
        this.idBooking = data().deepCopy(fields()[0].schema(), other.idBooking);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing CreateBookingAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.idBooking)) {
        this.idBooking = data().deepCopy(fields()[0].schema(), other.idBooking);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'idBooking' field.
      * @return The value.
      */
    public java.lang.CharSequence getIdBooking() {
      return idBooking;
    }


    /**
      * Sets the value of the 'idBooking' field.
      * @param value The value of 'idBooking'.
      * @return This builder.
      */
    public br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder setIdBooking(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.idBooking = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idBooking' field has been set.
      * @return True if the 'idBooking' field has been set, false otherwise.
      */
    public boolean hasIdBooking() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idBooking' field.
      * @return This builder.
      */
    public br.com.baracho.hm.infrastructure.config.kafka.avro.CreateBookingAvro.Builder clearIdBooking() {
      idBooking = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateBookingAvro build() {
      try {
        CreateBookingAvro record = new CreateBookingAvro();
        record.idBooking = fieldSetFlags()[0] ? this.idBooking : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateBookingAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateBookingAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateBookingAvro>
    READER$ = (org.apache.avro.io.DatumReader<CreateBookingAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.idBooking);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.idBooking = in.readString(this.idBooking instanceof Utf8 ? (Utf8)this.idBooking : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.idBooking = in.readString(this.idBooking instanceof Utf8 ? (Utf8)this.idBooking : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










