spring:
  application:
    name: hotel-manager-api
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotel-manager-db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/hotel-manager-db
    schemas: public
    user: postgres
    password: postgres
    locations: classpath:/db/migration/ddl,db/migration/dml
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    topics:
      booking-created-pending-processing: booking-created-pending-processing
    listener:
      ack-mode: manual
    consumer:
      group-id: hotel-manager-api
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        schema.registry.url: "http://127.0.0.1:8081"
        specific.avro.reader: true
        value.deserializer.specific.avro.reader: true
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema.registry.url: "http://127.0.0.1:8081"
        specific.avro.reader: true
  thymeleaf:
    enabled: false

feign:
  integration:
    notification-manager: http://localhost:8083/api/v1